name: mapbox_navigation
description: A minimal Mapbox 3D navigation package for Flutter with turn-by-turn navigation and FPS-style camera.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^2.10.0
  geolocator: ^14.0.2
  http: ^1.5.0
  turf: ^0.0.10
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/location-puck.png
