name: mapbox_navigation_plus
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  mapbox_maps_flutter: ^2.12.0
  location: ^8.0.1
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/drapeau-darrivee.png
    - assets/car_marker.png
    - assets/car_marker_bg.png
    - assets/default-location-puck.png
    - assets/navigation-location-puck.png
    - assets/car_arrow.glb